/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupSeniorBuddyRouteImport } from './routes/signup.senior-buddy'
import { Route as SignupNewStudentRouteImport } from './routes/signup.new-student'
import { Route as OnboardingSeniorBuddyRouteImport } from './routes/onboarding.senior-buddy'
import { Route as OnboardingNewStudentRouteImport } from './routes/onboarding.new-student'
import { Route as BuddyIdRouteImport } from './routes/buddy.$id'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupSeniorBuddyRoute = SignupSeniorBuddyRouteImport.update({
  id: '/signup/senior-buddy',
  path: '/signup/senior-buddy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupNewStudentRoute = SignupNewStudentRouteImport.update({
  id: '/signup/new-student',
  path: '/signup/new-student',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSeniorBuddyRoute = OnboardingSeniorBuddyRouteImport.update({
  id: '/onboarding/senior-buddy',
  path: '/onboarding/senior-buddy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingNewStudentRoute = OnboardingNewStudentRouteImport.update({
  id: '/onboarding/new-student',
  path: '/onboarding/new-student',
  getParentRoute: () => rootRouteImport,
} as any)
const BuddyIdRoute = BuddyIdRouteImport.update({
  id: '/buddy/$id',
  path: '/buddy/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/buddy/$id': typeof BuddyIdRoute
  '/onboarding/new-student': typeof OnboardingNewStudentRoute
  '/onboarding/senior-buddy': typeof OnboardingSeniorBuddyRoute
  '/signup/new-student': typeof SignupNewStudentRoute
  '/signup/senior-buddy': typeof SignupSeniorBuddyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/buddy/$id': typeof BuddyIdRoute
  '/onboarding/new-student': typeof OnboardingNewStudentRoute
  '/onboarding/senior-buddy': typeof OnboardingSeniorBuddyRoute
  '/signup/new-student': typeof SignupNewStudentRoute
  '/signup/senior-buddy': typeof SignupSeniorBuddyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/buddy/$id': typeof BuddyIdRoute
  '/onboarding/new-student': typeof OnboardingNewStudentRoute
  '/onboarding/senior-buddy': typeof OnboardingSeniorBuddyRoute
  '/signup/new-student': typeof SignupNewStudentRoute
  '/signup/senior-buddy': typeof SignupSeniorBuddyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/matches'
    | '/profile'
    | '/buddy/$id'
    | '/onboarding/new-student'
    | '/onboarding/senior-buddy'
    | '/signup/new-student'
    | '/signup/senior-buddy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/matches'
    | '/profile'
    | '/buddy/$id'
    | '/onboarding/new-student'
    | '/onboarding/senior-buddy'
    | '/signup/new-student'
    | '/signup/senior-buddy'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/matches'
    | '/profile'
    | '/buddy/$id'
    | '/onboarding/new-student'
    | '/onboarding/senior-buddy'
    | '/signup/new-student'
    | '/signup/senior-buddy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  ProfileRoute: typeof ProfileRoute
  BuddyIdRoute: typeof BuddyIdRoute
  OnboardingNewStudentRoute: typeof OnboardingNewStudentRoute
  OnboardingSeniorBuddyRoute: typeof OnboardingSeniorBuddyRoute
  SignupNewStudentRoute: typeof SignupNewStudentRoute
  SignupSeniorBuddyRoute: typeof SignupSeniorBuddyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/senior-buddy': {
      id: '/signup/senior-buddy'
      path: '/signup/senior-buddy'
      fullPath: '/signup/senior-buddy'
      preLoaderRoute: typeof SignupSeniorBuddyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/new-student': {
      id: '/signup/new-student'
      path: '/signup/new-student'
      fullPath: '/signup/new-student'
      preLoaderRoute: typeof SignupNewStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/senior-buddy': {
      id: '/onboarding/senior-buddy'
      path: '/onboarding/senior-buddy'
      fullPath: '/onboarding/senior-buddy'
      preLoaderRoute: typeof OnboardingSeniorBuddyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/new-student': {
      id: '/onboarding/new-student'
      path: '/onboarding/new-student'
      fullPath: '/onboarding/new-student'
      preLoaderRoute: typeof OnboardingNewStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buddy/$id': {
      id: '/buddy/$id'
      path: '/buddy/$id'
      fullPath: '/buddy/$id'
      preLoaderRoute: typeof BuddyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  ProfileRoute: ProfileRoute,
  BuddyIdRoute: BuddyIdRoute,
  OnboardingNewStudentRoute: OnboardingNewStudentRoute,
  OnboardingSeniorBuddyRoute: OnboardingSeniorBuddyRoute,
  SignupNewStudentRoute: SignupNewStudentRoute,
  SignupSeniorBuddyRoute: SignupSeniorBuddyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
